# Generated by Django 2.2.24 on 2024-03-26 07:26

from django.db import migrations


def get_relocate_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        Owner.objects.get_or_create(name=flat.owner, owners_phonenumber=flat.owners_phonenumber,
                                    owner_pure_phone=flat.owner_pure_phone)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20240326_1020'),
    ]

    operations = [migrations.RunPython(get_relocate_owners)
    ]
