# Generated by Django 2.2.24 on 2024-03-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20240326_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='text_complaint',
            new_name='text',
        ),
    ]
